README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-4065
- Description
Use a more widely adopted MiniJSON lib version.
**Steps:**
=> Add reference to MiniJSON C# lib [TENJIN-4065]

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-4065
- Description
Fix typo. Update example.
**Steps:**
=> Fix typo.  Fix example code. [TENJIN-4065]

README.md
=> Update example code.

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-5567
- Make it clear that customers can just use connect method without using ATTrackingManager for iOS 14
- Separate out the part for ATTrackingManager and SKAdNetwork
**Steps:**
=> update unity sdk docs for ios 14

README.md, RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-6140
- Description
**Steps:**
=> update code example for conversion value [TENJIN-6140]

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-7144
- Description
**Steps:**
=> improve docs for cv implementation [TENJIN-7144]

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-7225
- Description
**Steps:**
=> Update link for conversion value implementation [TENJIN-7225]

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-7539
- Description
**Steps:**
=> add android note [TENJIN-7539]

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-7850
- Description
**Steps:**
=> add S2S, misc fixes [TENJIN-7850]

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-
- Description
**Steps:**
=> Update README [TENJIN-7581]

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-
- Description
**Steps:**
=> Update README to check for iOS14

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-8824
- Description
**Steps:**
=> update screenshot [TENJIN-8824]

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-
- Description
**Steps:**
=> Update NSAdvertisingAttributionReportEndpoint  config

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-9827
- Description
**Steps:**
=> update instruction for china android [TENJIN-9827]

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-10591
- Remove jcenter()
- Update dependencies versions
- Update Unity version
**Steps:**
=> [TENJIN-10591] Update section App Store to have parity with Android-SDK

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-10701
- Add a Blockquote of note for jcenter deprecation
**Steps:**
=> [TENJIN-10701] Add a Blockquote of note for jcenter deprecation

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-10240
- Update README.md file with content of demo project
**Steps:**
=> [TENJIN-10240] Update README.md file with content of demo project

README.md
- Refactor style changes iOS notes and Android notes
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-11084
- Add google playstore section
- Add amazon store section
- Add ATT subsections
- Add content on how to display ATT prompt to user 
**Steps:**
=> [TENJIN-11084] Update README.md file with ATT sections

README.md, RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-11201
- Update RELEASE_NOTES.md with version 1.12.11
- Update README.md with IronSource Integration
- Add IronSource ILRD section
- Add integration code for IronSource
**Steps:**
=> [TENJIN-11201] Update tenjin unity package to version 1.12.11

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-11621
- Description
**Steps:**
=> add ilrd pricing [TENJIN-11621]

README.md, RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-11207
- Update README.md with HyperBid integration
- Update RELEASE_NOTES.md with 1.12.12
**Steps:**
=> [TENJIN-11207] Update tenjin unity artefacts to 1.12.12

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-11701
- use better wording for ilrd
**Steps:**
=> use better wording for ilrd [TENJIN-11701]

README.md, RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-
- Update Release notes
- Update README with admob ILRD section
**Steps:**
=> [TENJIN-11213] Update unity sdk with 1.12.13

README.md, RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-11751
- Update RELEASE_NOTES.MD with 1.12.14
- Update README.MD file with refactors
- Change passive voice sentence to active voice
- Update URL link numbers
- Update unity sdk artefact
**Steps:**
=> [TENJIN-11751] Update unity sdk to 1.12.14

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-11772
- update wording for deferred_deeplink/attribution info
**Steps:**
=> update wording for deferred_deeplink/attribution info [TENJIN-11772]

RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-11872
- Update RELEASE_NOTES.md
**Steps:**
=> [TENJIN-11872] Update unity sdk with 1.12.15

RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-12044
- Update release notes with 1.12.16
- Update unity package with 1.12.16
**Steps:**
=> [TENJIN-12044] Update tenjin unity sdk to 1.12.16

README.md, RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-11161
- Update release notes file with 1.12.17 changes
- Update read me file with notes for mainTeamplate.gradle file.
**Steps:**
=> [TENJIN-11161] Update Tenjin Unity SDK with version 1.12.17

RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-12196
- Update Release notes with 1.12.18 changes
**Steps:**
=> [TENJIN-12196] Update Tenjin Unity package with 1.12.18

RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-12382
- Update README.md with release version 1.12.19
- Update tenjin unity package with version 1.12.19
**Steps:**
=> [TENJIN-12382] Update android sdk with 1.12.15

RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-12382
- Fix release artefacts of version 1.12.19
**Steps:**
=> [TENJIN-12382] Fix release artefacts of version 1.12.19

RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-12514
- Update Release notes with 1.12.20 changes
- Add public method GetAttributionInfo
**Steps:**
=> [TENJIN-12514] Update README with version 1.12.20

RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-13273
**Steps:**
=> [TENJIN-13273] Release Unity 1.12.22

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-13430
- deprecate updateConversionValue and registerAppForAdNetworkAttribution
**Steps:**
=> deprecate updateConversionValue and registerAppForAdNetworkAttribution [TENJIN-13430]

RELEASE_NOTES.md
=> Release 1.12.23

README.md, RELEASE_NOTES.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-15007
- Update documentation
- Update binary
**Steps:**
=> Release 1.12.24

README.md
- Add new SKAN 4.0 methods to the documentation
**Steps:**
=> Update SKAN 4.0 docs

RELEASE_NOTES.md
=> Release 1.12.27

RELEASE_NOTES.md
=> Release 1.12.29

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-14458
- rename ironsource mediation to Unity LevelPlay
**Steps:**
=> rename ironsource mediation to Unity LevelPlay

README.md
**JIRA**:
- https://adromance.atlassian.net/browse/TENJIN-16860
- add manifest permission for unity android
**Steps:**
=> add manifest permission for unity android [TENJIN-16860]

README.md
- Update new available methods documentation
**Steps:**
=> Update new available methods documentation

README.md
=> Update GDPR and DMA docs

README.md
=> Fix typo on demo project docs

RELEASE_NOTES.md
=> Release 1.15.11

RELEASE_NOTES.md
=> Release 1.15.12

RELEASE_NOTES.md
=> Release 1.15.13
